# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MiyagiRDBTools
                                 A QGIS plugin
 This plugin is tools for Miyagi RDB
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-05
        copyright            : 
        email                : 
        git sha              : 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MiyagiRDBTools class from file MiyagiRDBTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .miyagi_rdb_tools import MiyagiRDBTools
    return MiyagiRDBTools(iface)
